### ISSUE TITLE
Fix mobile responsive

### ISSUE THREAD

**Issue by mateonunez** [mateonunez/website#110]
With the new version, the mobile responsive has been broken a little bit.

**Comment by Osiris34** [comment]
I would like to help fix the issue. Can you help give me a little more information on the issue?

**Comment by mateonunez** [comment]
Hi @Osiris34, thank you so much! It would be great. 

The "Open Source" section has the Followers section. It uses the `follower-card` that should be fixed on devices with the screen width less than 900px. There is the specific module `follower-card.module.css`, working there you can find the bug.

The avatars of the followers should be displayed as a circle in mobile screens, like the large screens.

![Screenshot_2023-01-07-20-39-44-312-edit_com github android](https://user-images.githubusercontent.com/11861080/211167715-eb19c496-0daa-42db-98c3-15ccbf839706.jpg)

**Comment by Osiris34** [comment]
I would like to complete this one do you mind assigning it to me

**Comment by mateonunez** [comment]
Awesome! Keep in touch about anything.

**Comment by Osiris34** [comment]
Where is the file located at?

**Comment by mateonunez** [comment]
> Where is the file located at?

https://github.com/mateonunez/website/blob/main/components/github/cards/follower/follower-card.module.css

**Comment by mateonunez** [comment]
> > Where is the file located at?
> 
> https://github.com/mateonunez/website/blob/main/components/github/cards/follower/follower-card.module.css

Hey @Osiris34 did my reply help you?

**Comment by Osiris34** [comment]
Yes, thank you I am to make the follower images small and circular correct?

**Comment by mateonunez** [comment]
That's perfect, thanks. 🙏
